version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - bridge
    volumes:
      - /docker/gitea/gitea:/data
    ports:
      - "30000:3000"
      - "30001:22"
  server:
    image: postgres:postgres:latest
    environment:
      - POSTGRES_USER=gitea_user
      - POSTGRES_PASSWORD=gitea_pass
      - POSTGRES_DB=gitea
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - bridge
    volumes:
      - /docker/gitea/postgresql:/var/lib/postgresql
    ports:
      - "30002:5432"
